-- Stores Gemini extraction output from CBC screenshots/images.
CREATE TABLE IF NOT EXISTS cbc_image_extractions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_image_name TEXT NOT NULL,
    source_image_path TEXT,
    occupancy_type TEXT,
    ownership_type TEXT,
    last_sale_date TEXT,
    primary_resident_name TEXT,
    primary_resident_age TEXT,
    primary_resident_phone_number TEXT,
    deceased_count INTEGER,
    important_notes TEXT,
    raw_extraction JSONB,
    raw_model_response TEXT,
    processed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_cbc_image_extractions_source_image_name
    ON cbc_image_extractions (source_image_name);
