-- BARN baseline, 4/6: research artifacts, outreach pipeline, scanner coordination.
-- All three are barn-only subsystems with no barn-scan counterpart.

-- ---------------------------------------------------------------------------
-- CyberBackgroundChecks screenshot extraction (ingest_cbc_images_to_supabase.py)
-- ---------------------------------------------------------------------------

-- The four match_* / matched_apn / property_address columns were missing from
-- the old schema even though ingest_cbc_images_to_supabase.py's audit_row has
-- always written them (see its --audit-table flag). Included here so the audit
-- path works without a follow-up migration.
create table cbc_image_extractions (
  id                            bigint generated by default as identity primary key,
  source_image_name             text not null unique,
  source_image_path             text,
  matched_apn                   text references bills(apn) on delete set null,
  match_status                  text,
  match_address_source          text,
  property_address              text,
  occupancy_type                text,
  ownership_type                text,
  last_sale_date                text,
  primary_resident_name         text,
  primary_resident_age          text,
  primary_resident_phone_number text,
  deceased_count                integer,
  important_notes               text,
  raw_extraction                jsonb,
  raw_model_response            text,
  processed_at                  timestamptz not null default now()
);

create index idx_cbc_extractions_matched_apn on cbc_image_extractions (matched_apn);

-- ---------------------------------------------------------------------------
-- Outreach pipeline (outreach_scorer.py, pitch_generator.py)
-- ---------------------------------------------------------------------------

create table outreach (
  id                 uuid primary key default gen_random_uuid(),
  apn                text not null unique references bills(apn) on delete cascade,
  stage              text not null default 'identified',
  outreach_score     real default 0,
  pitch_subject      text,
  pitch_draft        text,
  contacted_at       timestamptz,
  last_response_at   timestamptz,
  next_followup_at   timestamptz,
  followup_count     integer default 0,
  notes              text,
  openclaw_session_id text,
  owner_group_id     text,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create index idx_outreach_apn         on outreach (apn);
create index idx_outreach_stage       on outreach (stage);
create index idx_outreach_score       on outreach (outreach_score desc);
create index idx_outreach_owner_group on outreach (owner_group_id);

create table outreach_messages (
  id                  uuid primary key default gen_random_uuid(),
  apn                 text not null references bills(apn) on delete cascade,
  direction           text not null check (direction in ('inbound', 'outbound')),
  channel             text not null default 'email'
                        check (channel in ('email', 'whatsapp', 'phone', 'in_person')),
  subject             text,
  content             text,
  from_address        text,
  to_address          text,
  sent_at             timestamptz not null default now(),
  openclaw_message_id text
);

create index idx_outreach_messages_apn  on outreach_messages (apn);
create index idx_outreach_messages_sent on outreach_messages (sent_at desc);

-- SMTP config, score thresholds, and similar operator settings.
create table outreach_settings (
  key        text primary key,
  value      text not null,
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Scanner worker coordination (worker_state.py)
--
-- Scanners run on a VM, not on Vercel, and need to survive restarts. Jobs
-- record their own progress so an interrupted scan resumes where it stopped.
-- ---------------------------------------------------------------------------

create table scanner_workers (
  id             uuid primary key default gen_random_uuid(),
  name           text not null,
  last_heartbeat timestamptz,
  tunnel_url     text,
  status         text not null default 'offline' check (status in ('online', 'offline')),
  capabilities   jsonb,
  created_at     timestamptz not null default now()
);

create table scanner_jobs (
  id              uuid primary key default gen_random_uuid(),
  worker_id       uuid references scanner_workers(id) on delete set null,
  job_type        text not null,
  scope           jsonb,
  status          text not null check (status in ('running', 'interrupted', 'completed', 'failed')),
  started_at      timestamptz not null default now(),
  stopped_at      timestamptz,
  completed_at    timestamptz,
  current_city    text,
  current_apn     text,
  processed_count int not null default 0,
  hit_count       int not null default 0,
  error_summary   text,
  created_at      timestamptz not null default now()
);

create index idx_scanner_jobs_status on scanner_jobs (status, started_at desc);

create table scanner_job_checkpoints (
  id         uuid primary key default gen_random_uuid(),
  job_id     uuid not null references scanner_jobs(id) on delete cascade,
  city       text,
  apn        text,
  row_offset int,
  phase      text,
  extra      jsonb,
  created_at timestamptz not null default now()
);

create index idx_scanner_job_checkpoints_job on scanner_job_checkpoints (job_id, created_at desc);
